sudo: false
language: ruby
rvm:
  - 2.0
  - 2.1
  - 2.2
  - 2.3
  - 2.4
  - ruby-head
  - jruby-head
  - rbx-2
matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: rbx-2
before_install: gem install bundler
script:
  - bundle exec rake
  - cd spec/integration/rails && ./test-against-several-rails-versions.sh
